

/* This file contains the PRU instructions in a C array which are to  */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */

const unsigned int PRUcode[] =  {
     0x91042480,
     0x1d04e0e0,
     0x81042480,
     0x240010c0,
     0x24000080,
     0x240002c1,
     0x24202c81,
     0xe1002180,
     0x24abcde5,
     0x91083f84,
     0x24dcbae4,
     0x81083f84,
     0x2400231f,
     0x2a000000 };

